version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "tech-debt"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
